-- create "versioned_groups" table
CREATE TABLE "versioned_groups" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- create "versioned_users" table
CREATE TABLE "versioned_users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "age" integer NOT NULL, "name" character varying NOT NULL, "address" character varying NULL, PRIMARY KEY ("id"));
