version: "3.9"

services:
  database:
    image: cockroachdb/cockroach
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
  search:
    image: getmeili/meilisearch
    command: meilisearch --env="development"
    ports:
      - "7700:7700"