package services

import "errors"

var (
	ErrUsernameNotUnique          = errors.New("user with the specified username already exists")
	ErrEmailNotUnique             = errors.New("user with the specified email already exists")
	ErrFailedHashingPassword      = errors.New("failed hashing a password")
	ErrInvalidPasswordHash        = errors.New("invalid encoded password hash")
	ErrIncompatibleArgon2Version  = errors.New("incompatible argon2 version")
	ErrUnexpectedJWTSigningMethod = errors.New("unexpected JWT signing method")
	ErrInvalidRefreshToken        = errors.New("invalid refresh token")
	ErrInvalidAccessToken         = errors.New("invalid access token")
	ErrInvalidBearerToken         = errors.New("invalid bearer token")
	ErrFailedCreatingUser         = errors.New("failed creating a user")
	ErrInvalidEmail               = errors.New("invalid email address")
	ErrInvalidName                = errors.New("invalid name")
	ErrInvalidUsername            = errors.New("invalid username")
	ErrInvalidPassword            = errors.New("invalid password")
	ErrInvalidGender              = errors.New("invalid gender")
	ErrInvalidId                  = errors.New("invalid id")
	ErrCannotFollowTwiceSameUser  = errors.New("cannot follow twice the same user")
	ErrUserNotFound               = errors.New("user not found")
	ErrFollowNotFound             = errors.New("follow not found")
	ErrFollowerNotFound           = errors.New("follower not found")
	ErrFolloweeNotFound           = errors.New("followee not found")
	ErrBadRequest                 = errors.New("bad request")
	ErrInternalServerError        = errors.New("internal server error")
	ErrPostNotFound               = errors.New("post not found")
	ErrCannotLikeTwiceSamePost    = errors.New("cannot like twice the same post")
	ErrLikeNotFound               = errors.New("like not found")
)
