// Code generated by ent, DO NOT EDIT.

package ent

import (
	"socialite/ent/follow"
	"socialite/ent/schema"
	"socialite/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	followFields := schema.Follow{}.Fields()
	_ = followFields
	// followDescCreatedAt is the schema descriptor for created_at field.
	followDescCreatedAt := followFields[1].Descriptor()
	// follow.DefaultCreatedAt holds the default value on creation for the created_at field.
	follow.DefaultCreatedAt = followDescCreatedAt.Default.(func() time.Time)
	// followDescUpdatedAt is the schema descriptor for updated_at field.
	followDescUpdatedAt := followFields[2].Descriptor()
	// follow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	follow.DefaultUpdatedAt = followDescUpdatedAt.Default.(func() time.Time)
	// follow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	follow.UpdateDefaultUpdatedAt = followDescUpdatedAt.UpdateDefault.(func() time.Time)
	// followDescID is the schema descriptor for id field.
	followDescID := followFields[0].Descriptor()
	// follow.DefaultID holds the default value on creation for the id field.
	follow.DefaultID = followDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
