// Code generated by ent, DO NOT EDIT.

package ent

import (
	"socialite/ent/favourite"
	"socialite/ent/follow"
	"socialite/ent/like"
	"socialite/ent/post"
	"socialite/ent/schema"
	"socialite/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	favouriteFields := schema.Favourite{}.Fields()
	_ = favouriteFields
	// favouriteDescID is the schema descriptor for id field.
	favouriteDescID := favouriteFields[0].Descriptor()
	// favourite.DefaultID holds the default value on creation for the id field.
	favourite.DefaultID = favouriteDescID.Default.(func() uuid.UUID)
	followFields := schema.Follow{}.Fields()
	_ = followFields
	// followDescCreatedAt is the schema descriptor for created_at field.
	followDescCreatedAt := followFields[1].Descriptor()
	// follow.DefaultCreatedAt holds the default value on creation for the created_at field.
	follow.DefaultCreatedAt = followDescCreatedAt.Default.(func() time.Time)
	// followDescUpdatedAt is the schema descriptor for updated_at field.
	followDescUpdatedAt := followFields[2].Descriptor()
	// follow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	follow.DefaultUpdatedAt = followDescUpdatedAt.Default.(func() time.Time)
	// follow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	follow.UpdateDefaultUpdatedAt = followDescUpdatedAt.UpdateDefault.(func() time.Time)
	// followDescID is the schema descriptor for id field.
	followDescID := followFields[0].Descriptor()
	// follow.DefaultID holds the default value on creation for the id field.
	follow.DefaultID = followDescID.Default.(func() uuid.UUID)
	likeFields := schema.Like{}.Fields()
	_ = likeFields
	// likeDescID is the schema descriptor for id field.
	likeDescID := likeFields[0].Descriptor()
	// like.DefaultID holds the default value on creation for the id field.
	like.DefaultID = likeDescID.Default.(func() uuid.UUID)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[1].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postFields[2].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
