// Code generated by ent, DO NOT EDIT.

package follow

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the follow type in the database.
	Label = "follow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeFollower holds the string denoting the follower edge name in mutations.
	EdgeFollower = "follower"
	// EdgeFollowee holds the string denoting the followee edge name in mutations.
	EdgeFollowee = "followee"
	// UserFieldID holds the string denoting the ID field of the User.
	UserFieldID = "old"
	// Table holds the table name of the follow in the database.
	Table = "follows"
	// FollowerTable is the table that holds the follower relation/edge.
	FollowerTable = "follows"
	// FollowerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	FollowerInverseTable = "users"
	// FollowerColumn is the table column denoting the follower relation/edge.
	FollowerColumn = "follow_follower"
	// FolloweeTable is the table that holds the followee relation/edge.
	FolloweeTable = "follows"
	// FolloweeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	FolloweeInverseTable = "users"
	// FolloweeColumn is the table column denoting the followee relation/edge.
	FolloweeColumn = "follow_followee"
)

// Columns holds all SQL columns for follow fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "follows"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"follow_follower",
	"follow_followee",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
