// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Follow is the predicate function for follow builders.
type Follow func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
